default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: postgresnacha
  pool: 5

development:
  <<: *default
  database: grupo13_development


test:
  <<: *default
  database: grupo13_test
