default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  host: localhost
  password: hola
  pool: 5

development:
  <<: *default
  database: grupo13_development


test:
  <<: *default
  database: grupo13_test
